language: android

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew :app:testDebug :app:connectedAndroidTest -PtravisCi -PdisablePreDex